apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management
  namespace: ecommerce-dev
  labels:
    app: order-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-management
  template:
    metadata:
      labels:
        app: order-management
    spec:
      containers:
      - name: order-management
        image: bestproject2-order-management:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9000
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-order:5432/orderdb"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "postgres"
        - name: SERVER_PORT
          value: "9000"

---
apiVersion: v1
kind: Service
metadata:
  name: order-management
  namespace: ecommerce-dev
spec:
  type: NodePort
  selector:
    app: order-management
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 30082